CREATE DATABASE IF NOT EXISTS bravo4fun;

USE bravo4fun;

CREATE TABLE `USUARIO` (
  `USUARIO_ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_NOME` varchar(500) NOT NULL,
  `USUARIO_EMAIL` varchar(500) NOT NULL,
  `USUARIO_SENHA` varchar(500) NOT NULL,
  `USUARIO_CPF` varchar(11) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ADMINISTRADOR` (
  `ADM_ID` int NOT NULL AUTO_INCREMENT,
  `ADM_NOME` varchar(500) NOT NULL,
  `ADM_EMAIL` varchar(500) NOT NULL,
  `ADM_SENHA` varchar(500) NOT NULL,
  `ADM_ATIVO` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ADM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CATEGORIA` (
  `CATEGORIA_ID` int NOT NULL AUTO_INCREMENT,
  `CATEGORIA_NOME` varchar(500) NOT NULL,
  `CATEGORIA_DESC` varchar(8000) NOT NULL,
  `CATEGORIA_ATIVO` bit(1) DEFAULT b'1',
  PRIMARY KEY (`CATEGORIA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUTO` (
  `PRODUTO_ID` int NOT NULL AUTO_INCREMENT,
  `PRODUTO_NOME` varchar(500) NOT NULL,
  `PRODUTO_DESC` varchar(8000) NOT NULL,
  `PRODUTO_PRECO` decimal(5,2) NOT NULL,
  `PRODUTO_DESCONTO` decimal(5,2) NOT NULL,
  `CATEGORIA_ID` int NOT NULL,
  `PRODUTO_ATIVO` bit(1) NOT NULL,
  PRIMARY KEY (`PRODUTO_ID`),
  KEY `FK_CATEGORIA_PRODUTO` (`CATEGORIA_ID`),
  CONSTRAINT `FK_CATEGORIA_PRODUTO` FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `CATEGORIA` (`CATEGORIA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUTO_ESTOQUE` (
  `PRODUTO_ID` int NOT NULL,
  `PRODUTO_QTD` int NOT NULL,
  KEY `FK_PRODUTO_PRODUTO_ESTOQUE` (`PRODUTO_ID`),
  CONSTRAINT `FK_PRODUTO_PRODUTO_ESTOQUE` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `PRODUTO` (`PRODUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PRODUTO_IMAGEM` (
  `IMAGEM_ID` int NOT NULL AUTO_INCREMENT,
  `IMAGEM_ORDEM` int NOT NULL,
  `PRODUTO_ID` int NOT NULL,
  `IMAGEM_URL` varchar(8000) DEFAULT NULL,
  PRIMARY KEY (`IMAGEM_ID`),
  KEY `FK_PRODUTO_PRODUTO_IMAGEM` (`PRODUTO_ID`),
  CONSTRAINT `FK_PRODUTO_PRODUTO_IMAGEM` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `PRODUTO` (`PRODUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CARRINHO_ITEM` (
  `USUARIO_ID` int NOT NULL,
  `PRODUTO_ID` int NOT NULL,
  `ITEM_QTD` int NOT NULL,
  KEY `FK_PRODUTO_CARRINHO_ITEM` (`PRODUTO_ID`),
  KEY `FK_USUARIO_CARRINHO_ITEM` (`USUARIO_ID`),
  CONSTRAINT `FK_PRODUTO_CARRINHO_ITEM` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `PRODUTO` (`PRODUTO_ID`),
  CONSTRAINT `FK_USUARIO_CARRINHO_ITEM` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`USUARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ENDERECO` (
  `ENDERECO_ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `ENDERECO_NOME` varchar(500) NOT NULL,
  `ENDERECO_LOGRADOURO` varchar(500) NOT NULL,
  `ENDERECO_NUMERO` varchar(500) NOT NULL,
  `ENDERECO_COMPLEMENTO` varchar(500) DEFAULT NULL,
  `ENDERECO_CEP` varchar(8) NOT NULL,
  `ENDERECO_CIDADE` varchar(500) NOT NULL,
  `ENDERECO_ESTADO` varchar(2) NOT NULL,
  `ENDERECO_APAGADO` bit(1) DEFAULT b'0',
  PRIMARY KEY (`ENDERECO_ID`),
  KEY `FK_USUARIO_ENDERECO` (`USUARIO_ID`),
  CONSTRAINT `FK_USUARIO_ENDERECO` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`USUARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PEDIDO_STATUS` (
  `STATUS_ID` int NOT NULL AUTO_INCREMENT,
  `STATUS_DESC` varchar(500) NOT NULL,
  PRIMARY KEY (`STATUS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
insert into `PEDIDO_STATUS` (`STATUS_DESC`, `STATUS_ID`) values ('Em análise', 1);

CREATE TABLE `PEDIDO` (
  `PEDIDO_ID` int NOT NULL AUTO_INCREMENT,
  `USUARIO_ID` int NOT NULL,
  `STATUS_ID` int NOT NULL,
  `PEDIDO_DATA` date NOT NULL,
  PRIMARY KEY (`PEDIDO_ID`),
  KEY `FK_USUARIO_PEDIDO` (`USUARIO_ID`),
  KEY `FK_PEDIDO_STATUS_PEDIDO` (`STATUS_ID`),
  CONSTRAINT `FK_PEDIDO_STATUS_PEDIDO` FOREIGN KEY (`STATUS_ID`) REFERENCES `PEDIDO_STATUS` (`STATUS_ID`),
  CONSTRAINT `FK_USUARIO_PEDIDO` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`USUARIO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PEDIDO_ITEM` (
  `PRODUTO_ID` int NOT NULL,
  `PEDIDO_ID` int NOT NULL,
  `ITEM_QTD` int NOT NULL,
  `ITEM_PRECO` decimal(5,2) NOT NULL,
  KEY `FK_PRODUTO_PEDIDO_ITEM` (`PRODUTO_ID`),
  KEY `FK_PEDIDO_PEDIDO_ITEM` (`PEDIDO_ID`),
  CONSTRAINT `FK_PEDIDO_PEDIDO_ITEM` FOREIGN KEY (`PEDIDO_ID`) REFERENCES `PEDIDO` (`PEDIDO_ID`),
  CONSTRAINT `FK_PRODUTO_PEDIDO_ITEM` FOREIGN KEY (`PRODUTO_ID`) REFERENCES `PRODUTO` (`PRODUTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO 
	ADMINISTRADOR 
		(ADM_NOME, ADM_EMAIL, ADM_SENHA, ADM_ATIVO)
	SELECT 
		'Felipe Silva', 
        'felipe@bravo4fun.com.br', 
        '40bd001563085fc35165329ea1ff5c5ecbdbbeef', 
        1
	WHERE 
		NOT EXISTS (
			SELECT 1 FROM ADMINISTRADOR WHERE ADM_EMAIL = 'felipe@bravo4fun.com.br'
		);
